{% set name = "tensortrade" %}
{% set version = "1.0.4" %}
{% set python_min = "3.12" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 39c21afa66c63acfa303aba6e13874f1747b1ca8a25f28d9f0a8d34c6fd5d346

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - gymnasium >=0.28.1
    - ipython >=7.12.0
    - matplotlib-base >=3.1.1
    - numpy >=1.26.4
    - pandas 2.2.3,<3.0
    - plotly >=4.5.0
    - python >={{ python_min }}
    - pyyaml >=5.1.2
    - stochastic >=0.6.0
    - tensorflow >=2.15.1
    - deprecated >=1.2.13
    - ta >=0.4.7
    - pytest >=7.0.0

test:
  imports:
    - tensortrade
    - tensortrade.agents
  commands:
    - pytest
  requires:
    - pytest >=5.1.1
    - ta >=0.4.7
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://www.tensortrade.org
  summary: 'TensorTrade: A reinforcement learning library for training, evaluating, and deploying robust trading agents.'
  description: |
    TensorTrade is an open source Python framework for building, training, evaluating, and deploying robust trading
    algorithms using reinforcement learning. The framework focuses on being highly composable and extensible, to
    allow the system to scale from simple trading strategies on a single CPU, to complex investment
    strategies run on a distribution of HPC machines.
  license: Apache-2.0
  license_file: LICENSE
  dev_url: https://github.com/tensortrade-org/tensortrade
  doc_url: https://www.tensortrade.org/en/latest/overview/getting_started.html

extra:
  recipe-maintainers:
    - BastianZim
